" General {{{
set nocompatible                  " be iMproved

set history=256

set clipboard=unnamedplus         " use clipboard instead of register
set clipboard+=autoselect         " use system native clipboard

" title of the terminal window
"let &titlestring="%t"."%( (%{expand(\"%:~:h\")})%)"."%( %a%r%m%)"
let &titlestring="%t"."%( (%{expand(\"%:~:h\")})%)"
let &titlestring="%t"."%( %a%r%m%)"
if !has('gui_running')
  let &t_ts = "\e]0;"
  let &t_fs = "\007"
endif
if $PYENV_VERSION != "mutt"
  set title
endif

set nobackup
set nowritebackup

set cursorline

set modeline
set modelines=5

set t_Co=256

let g:is_posix = 1                " to use modern shell
let mapleader = ','

set tags=./tags;$HOME

set fileformats=unix,dos,mac

set ttyfast
" }}}

" Formatting {{{
set formatoptions=tcroqB

set textwidth=0

set backspace=indent,eol,start

set autoindent
au FileType c set cindent
set indentkeys-=0#                " do not break indent on #
set cinkeys-=0#
set cinoptions=:s,ps,ts,cs
set cinwords=if,else,while,do
set cinwords+=for,switch,case
"}}}

" Search {{{
set incsearch                     " incremental search
set hlsearch                      " highlight search
set ignorecase
set smartcase                     " i don't like ignorecase

" make search results appear in the middle of the screen
nmap n nzz
nmap N Nzz
nmap * *zz
nmap # #zz
nmap g* g*zz
nmap g# g#zz
"}}}

" Encoding {{{
set encoding=utf-8
set termencoding=utf-8
set fileencodings=utf-8,iso-2022-jo,us_ascii,sjis,eus-jp
"set ambiwidth=double
set ambiwidth=single
"}}}

" Win32 {{{
if has('win32')
  set langmenu=en_US
  let $LANG='en_US'
  source $VIMRUNTIME/delmenu.vim
  source $VIMRUNTIME/menu.vim
  if has('gui_running')
    set iminsert=0
    set imsearch=0
  endif
  set shell=C:/MinGW/msys/1.0/bin/mintty.exe\ /bin/bash\ --login
endif
"}}}

" Visual {{{
syntax on

set mouse=a
set mousehide                     " hide mouse after chars typed

" list
set list
set listchars=tab:>-
set listchars+=trail:=
"set listchars+=eol:¬
set listchars+=extends:»,precedes:«
map <silent> <leader>L :set invlist<CR>

" status line
set laststatus=2
"set statusline=%<%f\              " custom statusline
"set stl+=[%{&ff}]                 " show fileformat
"set stl+=[%{&fileencoding}]       " show fileencoding
"set stl+=%y%m%r%=
"set stl+=%-14.(%l,%c%V%)\ %P
"}}}

" Folding {{{
set foldenable
set foldmethod=marker             " fold on the marker ({{{ ... }}})
set foldlevel=100                 " disable autofold

set foldopen=block,hor,tag
set foldopen+=percent,mark
set foldopen+=quickfix
"}}}

" FileType {{{
au FileType javascript set expandtab ts=4 sw=4 sts=4
au FileType ruby set expandtab ts=2 sw=2 sts=2
au FileType perl set expandtab ts=2 sw=2 sts=2
au FileType python set expandtab ts=4 sw=4 sts=4
au FileType sh set expandtab ts=2 sw=2 sts=2
au FileType css set expandtab ts=2 sw=2 sts=2
au FileType htmlcheetah set expandtab ts=2 sw=2 sts=2
au FileType html set expandtab ts=2 sw=2 sts=2
au FileType xhtml set expandtab ts=2 sw=2 sts=2
au FileType jinja set expandtab ts=2 sw=2 sts=2
au FileType vim set expandtab ts=2 sw=2 sts=2
au FileType php set noexpandtab ts=8 sw=8 sts=8 " FuelPHP style
au FileType markdown set expandtab ts=4 sw=4 sts=4
autocmd BufRead,BufNewFile *.md setfiletype markdown

" 80 column layout - http://vim-users.jp/2011/05/hack217/
if exists('&colorcolumn')
  au FileType sh,c,python,javascript,ruby setlocal colorcolumn=+1 tw=80
  au FileType help setlocal colorcolumn=+1 tw=78
endif
"}}}

" key mapping {{{
"set number
map <silent> <leader>n :set invnumber<CR>

" reload firefox
if has('python')
  function! FirefoxReload()
python << EOF
import socket
import telnetlib
hostname = socket.gethostname()
if (hostname == 'tr808-squeeze' or hostname == 'tr909-squeeze'):
  # vim is running on vbox virtual machine
  host = '192.168.56.1' # vboxnet0 interface
else:
  host = 'localhost'
t = telnetlib.Telnet(host, 4242)
t.read_until('repl>', 2)
t.write('content.location.reload(true)\nrepl.quit()')
t.close()
EOF
  endfunction
  nmap <silent> <leader>r :call FirefoxReload()<CR>
endif

" run test
nmap <silent> <leader>t :!kill -SIGUSR1 `cat /tmp/run-test.pid`<CR><CR>

" create tag file using ptags.py
nmap <leader>p :! find -X . -name \*.py -print \| xargs ptags.py
" }}}

" Vundle {{{
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'

" my bundles:
Bundle 'Lokaltog/vim-powerline'
Bundle 'altercation/vim-colors-solarized'
"Bundle 'yuratomo/w3m.vim.git'
Bundle 'tyru/open-browser.vim.git'
Bundle 'thinca/vim-quickrun'
Bundle 'scrooloose/syntastic.git'
Bundle 'freitass/todo.txt-vim'
Bundle 'Markdown'
Bundle 'joker1007/vim-markdown-quote-syntax'
"Bundle 'kannokanno/previm.git'
Bundle 'tpope/vim-fugitive'
Bundle 'Glench/Vim-Jinja2-Syntax'

filetype plugin indent on

let g:vundle_default_git_proto = 'git'
" }}}

" appearance {{{
if has('gui_macvim')
  set transparency=4
  set guifont=Ricty\ Regular\ for\ Powerline:h12
endif
if has('gui_win32')
  set guifont=Ricty_for_Powerline:h14
  set linespace=0
endif

colorscheme solarized
set background=dark

if $HOSTNAME != "tb303"
  let g:Powerline_symbols = 'fancy'
endif
" }}}

" w3m.vim {{{
let g:w3m#command = "w3m"
" }}}

" open-browser.vim {{{
let g:netrw_nogx = 1 " disable netrw's gx mapping.
nmap gx <Plug>(openbrowser-smart-search)
vmap gx <Plug>(openbrowser-smart-search)
" }}}

" vim-quickrun {{{
silent! map <unique> <Leader>q <Plug>(quickrun)
let g:quickrun_config = {}
let g:quickrun_config.markdown = {
\ 'command': 'markdown.js',
\ 'exec': '%c < %s | html2text -nobs -style pretty -utf8'
\}
" }}}

" todo.txt-vim {{{
highlight default link TodoDone      Comment
highlight default link TodoPriorityA Type
highlight default link TodoPriorityB Statement
highlight default link TodoPriorityC Identifier
highlight default link TodoPriorityZ Comment
highlight default link TodoDate      PreProc
highlight default link TodoProject   Special
highlight default link TodoContext   String
" }}}
