# color support of ls
if [ "$TERM" != "dumb" ] && which dircolors > /dev/null; then
  eval "`dircolors -b`"
  alias ls='ls --color=auto'
fi

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize
